#!/bin/sh
# [Gedit Tool]
# Applicability=all
# Input=line
# Save-files=nothing
# Output=output-panel
# Name=Aktuálně

# Odkazy na dalsi tipy:
# 1) https://github.com/nagaozen/gedit-tunnings
echo '"'$GEDIT_CURRENT_DOCUMENT_DIR'"'
echo "$GEDIT_CURRENT_DOCUMENT_NAME"
echo "$GEDIT_SELECTED_TEXT"
