#!/bin/sh
# [Gedit Tool]
# Save-files=nothing
# Input=line
# Name=docWWW
# Output=output-panel
# Applicability=all
# Languages=fortran

cd "$GEDIT_CURRENT_DOCUMENT_DIR"
date +%H:%M:%S > temp.log
echo "$(cat temp.log) | Zobrazení FortranWiki, viz externí WWW prohlížeč NetRik."
rm "temp.log"
gnome-terminal -x bash -c 'netrik http://fortranwiki.org/fortran/search?query=$GEDIT_SELECTED_TEXT' 2> /dev/null

#http://www.fortran90.org/search.html?q=$GEDIT_CURRENT_WORD&check_keywords=yes&area=default
#http://www.fortran90.org/src/best-practices.html?highlight=$GEDIT_CURRENT_WORD
