#!/bin/sh
# [Gedit Tool]
# Applicability=all
# Input=nothing
# Save-files=nothing
# Name=freepascal
# Languages=pascal
# Shortcut=
# Output=output-panel

cd "$GEDIT_CURRENT_DOCUMENT_DIR"
date +%H:%M:%S > temp.log
echo "$(cat temp.log) | Kompilace souboru: $GEDIT_CURRENT_DOCUMENT_NAME"
rm "temp.log"

fpc -vv "$GEDIT_CURRENT_DOCUMENT_PATH" -o"$GEDIT_CURRENT_DOCUMENT_NAME.out" 2> "tempERR.log"

if [ -s tempERR.log ]
then
  echo "... neproběhla v pořádku, viz externí Terminál!"
  gnome-terminal -x bash -c 'cd "$GEDIT_CURRENT_DOCUMENT_DIR"; less tempERR.log' 2> /dev/null
else
  echo "... proběhla v pořádku!"
  rm "tempERR.log"
fi
