#!/bin/sh
# [Gedit Tool]
# Applicability=all
# Shortcut=F5
# Name=gfortran
# Save-files=nothing
# Output=output-panel
# Input=nothing
# Languages=fortran

cd "$GEDIT_CURRENT_DOCUMENT_DIR"
date +%H:%M:%S > temp.log
echo "$(cat temp.log) | Kompilace souboru: $GEDIT_CURRENT_DOCUMENT_NAME"
rm "temp.log"

gfortran "$GEDIT_CURRENT_DOCUMENT_PATH" -fcheck=all -o "$GEDIT_CURRENT_DOCUMENT_PATH.out" 2> "tempERR.log"

if [ -s tempERR.log ]
then
  echo "... neproběhla v pořádku, viz externí Terminál!"
  gnome-terminal --title="ERRORS LOG | Kompilace $GEDIT_CURRENT_DOCUMENT_NAME:" -x bash -c 'cd "$GEDIT_CURRENT_DOCUMENT_DIR"; less -p ":[0-9]*.[0-9]*:" tempERR.log' 2> /dev/null
else
  echo "... proběhla v pořádku!"
  rm "tempERR.log"
fi

#-fcheck=all
#-fcheck=all -g -fbounds-check -Wall -fbacktrace -finit-real=nan
