#!/bin/sh
# [Gedit Tool]
# Languages=markdown
# Output=output-panel
# Save-files=nothing
# Name=help
# Applicability=all
# Input=nothing

echo Nadpisy pomocí "#", "##", ...
echo Kurzíva obalit pomocí "*" či "_"
echo Tučně obalit pomocí "**" či "__"
echo Přeškrtnutí obalit pomocí "~"
echo Citace/Bloky pomocí ">"
echo 
echo Seznamy pomocí čísel, "*", "+" či "-"
echo Podseznamy pomocí dvojmezery "⋅⋅"
echo Pododstavec pomocí "⋅⋅⋅"
echo 
echo "[Text linku](link)"
echo "[Reference][číslo] ... [číslo]: link"
echo Obrázky pomocí přídání "!" před link
echo 
echo Kód obalit pomocí '"```"' resp. '"`"'
echo 
echo "| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | dolls 1600 |
| col 2 is      | centered      |   dolls 12 |
| zebra stripes | are neat      |    dolls 1 |"
