#!/bin/bash
# [Gedit Tool]
# Input=selection
# Name=html entities
# Save-files=nothing
# Output=replace-selection
# Applicability=all
# Languages=html,js,php

str=$(xargs)

if [[ ${#str} == 1 ]]
then
  echo "$str" | recode ..html
else
  echo "&$str"";" | recode html..
fi
