#!/usr/bin/env python
# [Gedit Tool]
# Applicability=all
# Output=replace-selection
# Name=Odstranit interpunkci
# Input=selection
# Save-files=nothing


import sys
import unicodedata

def not_combining(char):
    return unicodedata.category(char) != "Mn"

def strip_accents(text, encoding):
    unicode_text = unicodedata.normalize('NFD', text.decode(encoding))
    return filter(not_combining, unicode_text).encode(encoding)

print strip_accents(sys.stdin.read(), "UTF-8").lower().replace(' ', ' ')
