#!/bin/sh
# [Gedit Tool]
# Applicability=all
# Save-files=nothing
# Languages=python,python3
# Input=line
# Output=output-panel
# Name=doc

cd "$GEDIT_CURRENT_DOCUMENT_DIR"
date +%H:%M:%S > temp.log
echo "$(cat temp.log) | Zobrazení nápovědy, viz externí program pydoc."
rm "temp.log"
dokumentace=$(zenity --list --title="Zvolte knihovnu" \
--text="Zobrazit dokumentaci pro knihovnu:" \
--radiolist --column "Vybráno" --column "Knihovna" \
TRUE "numpy" FALSE "scipy" FALSE "matplotlib" FALSE "matplotlib.pyplot" FALSE "Jen Python" --separator=":")
if [ -z "$dokumentace" ]
then
  echo "Zrušeno"
elif [ "$dokumentace" = "Jen Python" ]
then
  pydoc "$GEDIT_SELECTED_TEXT" > tempDOC.log
else
  pydoc "$dokumentace" > tempDOC.log
fi
grep -oh "\b$GEDIT_SELECTED_TEXT\b" tempDOC.log | wc -w > temp.log
echo "Celkem $(cat temp.log) výskytů - viz následující přehled:" > temp.log
grep --color=always -nr "\b$GEDIT_SELECTED_TEXT\b" tempDOC.log >> temp.log
echo >> temp.log
echo "Celá dokumentace:" >> temp.log
egrep --color=always -nr "\b$GEDIT_SELECTED_TEXT\b|$" tempDOC.log >> temp.log
rm tempDOC.log
gnome-terminal --title="Dokumentace Pythonu | Vyhledávání '$GEDIT_SELECTED_TEXT':" -x bash -c 'cd "$GEDIT_CURRENT_DOCUMENT_DIR"; less -S -R -p "\b$GEDIT_SELECTED_TEXT\b" "temp.log"' 2> /dev/null
#search=`xargs -0 echo`
