#!/bin/sh
# [Gedit Tool]
# Applicability=all
# Input=nothing
# Save-files=nothing
# Name=run
# Languages=pascal
# Shortcut=
# Output=output-panel

cd "$GEDIT_CURRENT_DOCUMENT_DIR"
date +%H:%M:%S > temp.log
echo "$(cat temp.log) | Spuštění programu: $GEDIT_CURRENT_DOCUMENT_NAME.out"
rm "temp.log"

"$GEDIT_CURRENT_DOCUMENT_PATH.out" > "temp.log" 2> "tempERR.log"

if [ -s tempERR.log ]
then
  echo "... neproběhlo v pořádku, viz externí Terminál!"
  gnome-terminal -x bash -c 'cd "$GEDIT_CURRENT_DOCUMENT_DIR"; less tempERR.log' 2> /dev/null
else
  echo "... proběhlo v pořádku!"
  rm "tempERR.log"
fi

if [ -s temp.log ]
then
  gnome-terminal -x bash -c 'cd "$GEDIT_CURRENT_DOCUMENT_DIR"; less temp.log' 2> /dev/null
else
  rm "temp.log"  
fi
