#!/bin/sh
# [Gedit Tool]
# Name=Spustit příkaz
# Languages=
# Applicability=all
# Output=nothing
# Comment=Vykonat uživatelský příkaz a vložit jeho výstup do nového dokumentu
# Input=nothing
# Save-files=nothing


#TODO: use "gconftool-2 -g /desktop/gnome/applications/terminal/exec"
eval $(zenity --entry --title="Run Command - gedit" --text="Command to run:")
