#!/bin/sh
# [Gedit Tool]
# Name=run
# Save-files=nothing
# Input=nothing
# Languages=markdown
# Output=nothing
# Applicability=all

markdown "$GEDIT_CURRENT_DOCUMENT_PATH" > "$GEDIT_CURRENT_DOCUMENT_PATH.html"

sed -i -- 's/<p>..HTML..//g' "$GEDIT_CURRENT_DOCUMENT_PATH.html"
sed -i -- 's/..HTML..<\/p>//g' "$GEDIT_CURRENT_DOCUMENT_PATH.html"
