#!/bin/sh
# [Gedit Tool]
# Save-files=nothing
# Applicability=all
# Input=nothing
# Output=output-panel
# Name=stackoverflow

cd "$GEDIT_CURRENT_DOCUMENT_DIR"
date +%H:%M:%S > temp.log
echo "$(cat temp.log) | Zobrazení stackoverflow, viz externí WWW prohlížeč NetRik."
rm "temp.log"
gnome-terminal -x bash -c 'ASK=`zenity --entry --title="Vyhledat na stackoverflow" --text="Hledaný výraz ([] indikují tagy):"`; netrik http://stackoverflow.com/search?q="$ASK"' 2> /dev/null
#http://stackoverflow.com/search?q=[bash]+calculator
