#!/bin/sh
# [Gedit Tool]
# Applicability=all
# Languages=python,python3
# Save-files=nothing
# Name=run
# Shortcut=
# Input=nothing
# Output=output-panel

cd "$GEDIT_CURRENT_DOCUMENT_DIR"
date +%H:%M:%S > temp.log
echo "$(cat temp.log) | Spuštění souboru: $GEDIT_CURRENT_DOCUMENT_NAME"
rm "temp.log"

python "$GEDIT_CURRENT_DOCUMENT_PATH" > "temp.log" 2> "tempERR.log"

if [ -s tempERR.log ]
then
  echo "... neproběhlo v pořádku, viz externí Terminál!"
  gnome-terminal --title="ERRORS LOG | $GEDIT_CURRENT_DOCUMENT_NAME:" -x bash -c 'cd "$GEDIT_CURRENT_DOCUMENT_DIR"; less tempERR.log' 2> /dev/null
else
  echo "... proběhlo v pořádku!"
  rm "tempERR.log"
fi

if [ -s temp.log ]
then
  gnome-terminal --title="Terminálový výstup | $GEDIT_CURRENT_DOCUMENT_NAME:" -x bash -c 'cd "$GEDIT_CURRENT_DOCUMENT_DIR"; less temp.log' 2> /dev/null
else
  rm "temp.log"  
fi
